# Generated by Django 5.1 on 2024-08-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_mycourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourses',
            old_name='event',
            new_name='course',
        ),
    ]
