# Generated by Django 5.1 on 2024-08-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_event_mycourses_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourses',
            old_name='course',
            new_name='patata',
        ),
    ]
