# Generated by Django 5.1 on 2024-08-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_course_mycourses_patata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourses',
            old_name='patata',
            new_name='course',
        ),
    ]
